name: CI

on: [push]

jobs:
  image: ubuntu:18.04

  before_script:
    - apt-get update -qy
    - apt-get install -y lftp

  build:
    script:
      # Sync to FTP
      - lftp -e "open 35.235.124.140 -p 17771 ; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete learndash-subsriber/ /www/senixejo_968/public/wp-content/plugins/learndash-subsriber/; bye"
